CREATE TABLE IF NOT EXISTS `drug_plants` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `x` FLOAT NOT NULL,
    `y` FLOAT NOT NULL,
    `z` FLOAT NOT NULL,
    `heading` FLOAT NOT NULL,
    `type` VARCHAR(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
    `waterLevel` FLOAT NOT NULL DEFAULT 10,
    `fertilizerLevel` FLOAT NOT NULL DEFAULT 10,
    `time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `lastUpdated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;